apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: web-frontend
        image: jvictorsm/frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-frontend
spec:
  selector:
    app: web-frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort

