x-db-credentials: &db-credentials
  POSTGRES_USER: &db-user ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: &db-password ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: &db-name ${POSTGRES_DB:-postgres}

services:
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: react-app
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app

  backend:
    build: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      DB_USER: *db-user
      DB_PASSWORD: *db-password
      DB_NAME: *db-name
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app
      - postgres
      - redis
  postgres:
    image: postgres:15.10
    container_name: postgres
    environment:
      <<: *db-credentials
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres

  redis:
    image: redis:8.2.1
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - redis

networks:
  app:
    driver: bridge
  redis:
    driver: bridge
  postgres:
    driver: bridge