kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 38080
        protocol: TCP
      - containerPort: 30000
        hostPort: 38000
        protocol: TCP
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker